(sync) Resolve conflicts with gatsby-i18n-source @ 90932a0
gatsbyjs/gatsby-ru pull request #38
Opened 2020-02-19 21:27 UTC by gatsbybot

Sync conflicts with the source repo. Please update the translations based on updated source content.

For more information on how to resolve sync conflicts, check out the [guide for syncing translations](https://gatsbyjs.org/contributing/translations/sync-guide/).

<details >
<summary>The following 23 files have conflicts:</summary><br />

* [ ] docs/tutorial/wordpress-source-plugin-tutorial.md
* [ ] docs/tutorial/using-a-theme.md
* [ ] docs/docs/using-graphql-playground.md
* [ ] docs/docs/upgrading-node-js.md
* [ ] docs/docs/typography-js.md
* [ ] docs/docs/sourcing-from-buttercms.md
* [ ] docs/docs/quick-start.md
* [ ] docs/docs/preparing-your-environment.md
* [ ] docs/docs/path-prefix.md
* [ ] docs/docs/mdx/programmatically-creating-pages.md
* [ ] docs/docs/index.md
* [ ] docs/docs/how-shadowing-works.md
* [ ] docs/docs/gatsby-lifecycle-apis.md
* [ ] docs/docs/gatsby-cli.md
* [ ] docs/docs/bulma.md
* [ ] docs/docs/building-an-e-commerce-site.md
* [ ] docs/docs/browser-support.md
* [ ] docs/docs/babel.md
* [ ] docs/docs/audit-with-lighthouse.md
* [ ] docs/docs/adding-search-with-elasticlunr.md
* [ ] docs/docs/add-custom-webpack-config.md
* [ ] docs/docs/add-404-page.md
* [ ] docs/contributing/organize-a-gatsby-event.md
</details>

Once all the commits have been fixed, mark this pull request as "Ready for review" and merge it in!

See all changes since the last sync here:

https://github.com/gatsbyjs/gatsby-i18n-source/compare/d7eb748..90932a0

NOTE: Do **NOT** squash-merge this pull request. The sync script requires a ref to the source repo in order to work correctly.

## Related PRs

#37 PR for syncing non-conflicting files

2020-02-19 21:46 UTC, tesseralis requested changes
Hi @lex111 @alexandrtovmach! I created a sync PR for you. Most of the changes were formatting changes in the English version, so I duplicated those changes here. There are just 2-3 files that have text that needs to be translated again.

~@tesseralis

2020-02-19 21:46 UTC, tesseralis commented on docs/docs/quick-start.md
> +> The above command installs Gatsby CLI globally on your machine.
Please translate this text.

2020-02-19 21:46 UTC, tesseralis commented on docs/docs/index.md
> +description: The one stop location for tutorials, guides, and information about building with Gatsby
Please translate this description.

2020-08-15 16:04 UTC, alexandrtovmach reviewed
Translated requested texts

2020-08-15 16:04 UTC, alexandrtovmach commented on docs/docs/index.md
> +description: The one stop location for tutorials, guides, and information about building with Gatsby
```suggestion
description: Единое место для учебных пособий, руководств и информации по работе с Gatsby
```

2020-08-15 16:04 UTC, alexandrtovmach commented on docs/docs/quick-start.md
> +> The above command installs Gatsby CLI globally on your machine.
```suggestion
> Приведенная выше команда устанавливает Gatsby CLI глобально на ваш компьютер.
```

2025-01-20 16:38 UTC, closed without merging