tutorial/part-three
gatsbyjs/gatsby-ru pull request #39
Opened 2020-02-26 08:35 UTC by RinatRezyapov

1. layout components по [Словарь терминов по фронтенду](https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md) переводится как **компоненты раскладки**. Я использовал **компоненты разметки**, так как **компоненты раскладки**, по моему мнению, режет слух. TBD.

2020-02-27 09:56 UTC, alexandrtovmach commented on docs/tutorial/part-three/index.md
> +> У нас уже сотни плагинов! Узнайте о [Библиотеке Gatsby плагинов больше](/plugins/).
```suggestion
> У нас уже сотни плагинов! Откройте для себя [Библиотеку Плагинов](/plugins/) Gatsby.
```

2020-02-27 10:08 UTC, alexandrtovmach requested changes

2020-02-27 10:08 UTC, alexandrtovmach commented on docs/tutorial/part-three/index.md
> +`gatsby-config.js` это ещё один специальный файл который Gatsby автоматически распознает. В этом файле обычно содержатся плагины и другие настройки сайта.
```suggestion
`gatsby-config.js` это ещё один специальный файл, который автоматически распознается Gatsby. В нём обычно содержатся плагины и другие настройки сайта.
```

2020-02-27 10:08 UTC, alexandrtovmach commented on docs/tutorial/part-three/index.md
> +3. Typography.js требует файла настроек. Создайте новую папку под названием `utils` в `src` директории. Затем создайте новый файл под названием `typography.js` в папке `utils` и скопируйте в этот фай
```suggestion
3. Typography.js требует файла настроек. Создайте новую папку `utils` внутри папки `src`. Затем создайте новый файл под названием `typography.js` в папке `utils` и скопируйте в него следующее содержимое:
```

2020-02-27 10:08 UTC, alexandrtovmach commented on docs/tutorial/part-three/index.md
> +Как только сайт загрузится используйте средства разработки Chrome чтобы проинспектировать сгенерированный HTML, вы увидите что плагин типографики добавил `<style>` элемент с сгенерированным CSS в `<h
```suggestion
Как только сайт загрузится и если вы используйте средства разработки Chrome для инпектирования сгенерированного HTML, то вы увидите что плагин типографики добавил `<style>` элемент со сгенерированным CSS в `<head>` элемент:
```

2020-02-27 10:08 UTC, alexandrtovmach commented on docs/tutorial/part-three/index.md
> +Скопируйте следующее содержимое в ваш `src/pages/index.js` файл чтобы вы могли увидеть эффект от применения CSS стилей сгенерированных библиотекой Typography.js.
```suggestion
Скопируйте следующее содержимое в ваш `src/pages/index.js` файл, чтобы увидеть эффект от применения CSS стилей сгенерированных библиотекой Typography.js.
```

2020-02-27 10:08 UTC, alexandrtovmach commented on docs/tutorial/part-three/index.md
> +Давайте посмотрим на то как выглядит страница:
```suggestion
Давайте посмотрим как выглядит страница:
```

2020-02-27 10:15 UTC, alexandrtovmach requested changes

2020-02-27 10:15 UTC, alexandrtovmach commented on docs/tutorial/part-three/index.md
> +Плагины Gatsby это JavaScript пакеты которые помогают добавлять функциональность Gatsby сайту. Gatsby спроектирован быть расширяемым, это означает что плагины могут расширять и изменять практически в
```suggestion
Плагины Gatsby это JavaScript пакеты, которые помогают добавлять функциональность Gatsby сайту. Gatsby спроектирован быть расширяемым, это означает что плагины могут расширять и изменять практически всё что Gatsby делает.
```

2020-02-27 10:15 UTC, alexandrtovmach commented on docs/tutorial/part-three/index.md
> +Участники сообщества (как вы!) могут принять участие в создании плагинов (представляющих из себя небольшое количество JavaScript кода) которые могут быть использованы другими пользователями при созда
```suggestion
Участники сообщества (как вы!) могут принять участие в создании плагинов (представляющих собой небольшое количество JavaScript кода) которые могут быть использованы другими пользователями при создании Gatsby сайтов.
```

2020-02-27 10:15 UTC, alexandrtovmach commented on docs/tutorial/part-three/index.md
> +[Typography.js](https://kyleamathews.github.io/typography.js/) это JavaScript библиотека которая создает глобальные стили для типографики вашего сайта. У этой библиотеки есть [соответствующий Gatsby
```suggestion
[Typography.js](https://kyleamathews.github.io/typography.js/) это JavaScript библиотека, которая создает глобальные стили для типографики вашего сайта. У этой библиотеки есть [соответствующий Gatsby плагин](/packages/gatsby-plugin-typography/), который упрощает её использование в Gatsby сайте.
```

2020-02-27 10:15 UTC, alexandrtovmach commented on docs/tutorial/part-three/index.md
> +3. Проимпортируйте вновь созданный компонент разметки в ваш `src/pages/index.js` компонент:
```suggestion
3. Импортируйте вновь созданный компонент разметки в ваш `src/pages/index.js` компонент:
```

2020-02-27 10:15 UTC, alexandrtovmach commented on docs/tutorial/part-three/index.md
> +4. Проимпортируйте компонент разметки в `about.js` и `contact.js` компоненты (так же как вы сделали это для `index.js` компонента ранее).
```suggestion
4. Импортируйте компонент разметки в `about.js` и `contact.js` компоненты (так же как вы сделали это для `index.js` компонента ранее).
```

2020-02-27 10:16 UTC, alexandrtovmach commented
@RinatRezyapov Большое спасибо за ваш вклад, после ревью несколько правок

2020-03-01 07:09 UTC, RinatRezyapov commented
> @RinatRezyapov Большое спасибо за ваш вклад, несколько правок после ревью

Спасибо! Сделал правки по замечаниям.

2020-04-08 13:48 UTC, alexandrtovmach approved these changes

2020-04-08 13:48 UTC, merged